# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-ButtonMaker
version:      0.1
version_from: lib/Image/ButtonMaker.pm
installdirs:  site
requires:
    Image::Magick:                 5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
